-- ============================================================
-- SCHEMA VERIFICATION QUERY
-- Run this in the NEW Supabase SQL editor (project jkzbuypbhqbssmqjpdtj)
-- It compares your current column definitions against the expected
-- Lovable schema and reports every mismatch.
-- ============================================================

WITH expected (table_name, column_name, data_type, is_nullable, has_default) AS (
  VALUES
  -- account_users
  ('account_users','id','uuid','NO',true),
  ('account_users','account_id','uuid','NO',false),
  ('account_users','user_id','uuid','NO',false),
  ('account_users','role','USER-DEFINED','NO',true),
  ('account_users','created_at','timestamp with time zone','NO',true),

  -- accounts
  ('accounts','id','uuid','NO',true),
  ('accounts','name','text','NO',false),
  ('accounts','account_type','text','YES',false),
  ('accounts','is_active','boolean','NO',true),
  ('accounts','created_at','timestamp with time zone','NO',true),
  ('accounts','updated_at','timestamp with time zone','NO',true),

  -- ad_account_profiles
  ('ad_account_profiles','id','uuid','NO',true),
  ('ad_account_profiles','ad_account_id','uuid','NO',false),
  ('ad_account_profiles','account_id','uuid','NO',false),
  ('ad_account_profiles','user_id','uuid','NO',false),
  ('ad_account_profiles','industry','text','YES',false),
  ('ad_account_profiles','facebook_page_id','text','YES',false),
  ('ad_account_profiles','facebook_page_name','text','YES',false),
  ('ad_account_profiles','confirmed','boolean','NO',true),
  ('ad_account_profiles','website_url','text','YES',false),
  ('ad_account_profiles','brand_name','text','YES',false),
  ('ad_account_profiles','logo_url','text','YES',false),
  ('ad_account_profiles','primary_color','text','YES',false),
  ('ad_account_profiles','secondary_color','text','YES',false),
  ('ad_account_profiles','accent_color','text','YES',false),
  ('ad_account_profiles','font_family','text','YES',false),
  ('ad_account_profiles','tone_of_voice','text','YES',false),
  ('ad_account_profiles','tagline','text','YES',false),
  ('ad_account_profiles','product_categories','ARRAY','YES',true),
  ('ad_account_profiles','brand_kit','jsonb','YES',true),
  ('ad_account_profiles','brand_kit_status','text','YES',true),
  ('ad_account_profiles','brand_kit_updated_at','timestamp with time zone','YES',false),
  ('ad_account_profiles','brand_guidelines_path','text','YES',false),
  ('ad_account_profiles','brand_guidelines_filename','text','YES',false),
  ('ad_account_profiles','brand_guidelines_uploaded_at','timestamp with time zone','YES',false),
  ('ad_account_profiles','brand_id','uuid','YES',false),
  ('ad_account_profiles','created_at','timestamp with time zone','NO',true),
  ('ad_account_profiles','updated_at','timestamp with time zone','NO',true),

  -- ad_accounts
  ('ad_accounts','id','uuid','NO',true),
  ('ad_accounts','connection_id','uuid','NO',false),
  ('ad_accounts','account_id','uuid','NO',false),
  ('ad_accounts','user_id','uuid','NO',false),
  ('ad_accounts','account_id_meta','text','NO',false),
  ('ad_accounts','account_name','text','NO',false),
  ('ad_accounts','currency','text','YES',true),
  ('ad_accounts','timezone','text','YES',false),
  ('ad_accounts','connection_status','text','NO',true),
  ('ad_accounts','onboarding_completed','boolean','NO',true),
  ('ad_accounts','created_at','timestamp with time zone','NO',true),
  ('ad_accounts','updated_at','timestamp with time zone','NO',true),

  -- ad_creatives
  ('ad_creatives','id','uuid','NO',true),
  ('ad_creatives','ad_id','uuid','NO',false),
  ('ad_creatives','account_id','uuid','NO',false),
  ('ad_creatives','user_id','uuid','NO',false),
  ('ad_creatives','meta_creative_id','text','NO',false),
  ('ad_creatives','creative_type','text','YES',false),
  ('ad_creatives','image_url','text','YES',false),
  ('ad_creatives','image_hash','text','YES',false),
  ('ad_creatives','image_hashes','jsonb','YES',false),
  ('ad_creatives','stored_image_url','text','YES',false),
  ('ad_creatives','stored_image_urls','jsonb','YES',false),
  ('ad_creatives','thumbnail_url','text','YES',false),
  ('ad_creatives','headline','text','YES',false),
  ('ad_creatives','primary_text','text','YES',false),
  ('ad_creatives','description','text','YES',false),
  ('ad_creatives','destination_url','text','YES',false),
  ('ad_creatives','cta_type','text','YES',false),
  ('ad_creatives','raw_data','jsonb','YES',false),
  ('ad_creatives','raw_object_story_spec','jsonb','YES',false),
  ('ad_creatives','raw_asset_feed_spec','jsonb','YES',false),
  ('ad_creatives','created_at','timestamp with time zone','NO',true),
  ('ad_creatives','updated_at','timestamp with time zone','NO',true),

  -- ad_performance_daily
  ('ad_performance_daily','id','uuid','NO',true),
  ('ad_performance_daily','ad_id','uuid','NO',false),
  ('ad_performance_daily','account_id','uuid','NO',false),
  ('ad_performance_daily','user_id','uuid','NO',false),
  ('ad_performance_daily','date','date','NO',false),
  ('ad_performance_daily','platform','text','YES',false),
  ('ad_performance_daily','platform_position','text','YES',false),
  ('ad_performance_daily','impressions','numeric','YES',false),
  ('ad_performance_daily','clicks','numeric','YES',false),
  ('ad_performance_daily','spend','numeric','YES',false),
  ('ad_performance_daily','reach','numeric','YES',false),
  ('ad_performance_daily','frequency','numeric','YES',false),
  ('ad_performance_daily','ctr','numeric','YES',false),
  ('ad_performance_daily','unique_ctr','numeric','YES',false),
  ('ad_performance_daily','cpc','numeric','YES',false),
  ('ad_performance_daily','cpm','numeric','YES',false),
  ('ad_performance_daily','purchases','numeric','YES',false),
  ('ad_performance_daily','revenue','numeric','YES',false),
  ('ad_performance_daily','roas','numeric','YES',false),
  ('ad_performance_daily','cost_per_purchase','numeric','YES',false),
  ('ad_performance_daily','thumb_stop_rate','numeric','YES',false),
  ('ad_performance_daily','result_type','text','YES',false),
  ('ad_performance_daily','created_at','timestamp with time zone','NO',true),
  ('ad_performance_daily','updated_at','timestamp with time zone','NO',true),

  -- ad_sets
  ('ad_sets','id','uuid','NO',true),
  ('ad_sets','campaign_id','uuid','NO',false),
  ('ad_sets','account_id','uuid','NO',false),
  ('ad_sets','user_id','uuid','NO',false),
  ('ad_sets','meta_adset_id','text','NO',false),
  ('ad_sets','name','text','YES',false),
  ('ad_sets','status','text','YES',false),
  ('ad_sets','effective_status','text','YES',false),
  ('ad_sets','daily_budget','numeric','YES',false),
  ('ad_sets','lifetime_budget','numeric','YES',false),
  ('ad_sets','billing_event','text','YES',false),
  ('ad_sets','optimization_goal','text','YES',false),
  ('ad_sets','targeting','jsonb','YES',false),
  ('ad_sets','start_time','timestamp with time zone','YES',false),
  ('ad_sets','end_time','timestamp with time zone','YES',false),
  ('ad_sets','created_at','timestamp with time zone','NO',true),
  ('ad_sets','updated_at','timestamp with time zone','NO',true),

  -- ads
  ('ads','id','uuid','NO',true),
  ('ads','ad_set_id','uuid','NO',false),
  ('ads','account_id','uuid','NO',false),
  ('ads','user_id','uuid','NO',false),
  ('ads','meta_ad_id','text','NO',false),
  ('ads','meta_creative_id','text','YES',false),
  ('ads','name','text','YES',false),
  ('ads','status','text','YES',false),
  ('ads','effective_status','text','YES',false),
  ('ads','media_type','text','YES',false),
  ('ads','parent_ad_id','uuid','YES',false),
  ('ads','created_at','timestamp with time zone','NO',true),
  ('ads','updated_at','timestamp with time zone','NO',true),

  -- brand_archetypes
  ('brand_archetypes','id','uuid','NO',true),
  ('brand_archetypes','account_id','uuid','NO',false),
  ('brand_archetypes','brand_id','uuid','NO',false),
  ('brand_archetypes','archetype_id','uuid','NO',false),
  ('brand_archetypes','user_id','uuid','NO',false),
  ('brand_archetypes','ad_type','text','YES',false),
  ('brand_archetypes','is_permitted','boolean','NO',true),
  ('brand_archetypes','created_at','timestamp with time zone','NO',true),
  ('brand_archetypes','updated_at','timestamp with time zone','NO',true),

  -- brand_competitors
  ('brand_competitors','id','uuid','NO',true),
  ('brand_competitors','account_id','uuid','NO',false),
  ('brand_competitors','brand_id','uuid','YES',false),
  ('brand_competitors','user_id','uuid','NO',false),
  ('brand_competitors','ad_account_id','uuid','YES',false),
  ('brand_competitors','competitor_name','text','YES',false),
  ('brand_competitors','competitor_meta_page_id','text','YES',false),
  ('brand_competitors','competitor_meta_page_name','text','YES',false),
  ('brand_competitors','foreplay_brand_id','text','YES',false),
  ('brand_competitors','industry','text','YES',false),
  ('brand_competitors','website_url','text','YES',false),
  ('brand_competitors','logo_url','text','YES',false),
  ('brand_competitors','is_active','boolean','NO',true),
  ('brand_competitors','created_at','timestamp with time zone','NO',true),
  ('brand_competitors','updated_at','timestamp with time zone','NO',true),

  -- brands
  ('brands','id','uuid','NO',true),
  ('brands','account_id','uuid','NO',false),
  ('brands','ad_account_id','uuid','YES',false),
  ('brands','user_id','uuid','NO',false),
  ('brands','name','text','NO',false),
  ('brands','category','text','YES',false),
  ('brands','target_regions','text','YES',false),
  ('brands','target_languages','text','YES',false),
  ('brands','created_at','timestamp with time zone','NO',true),
  ('brands','updated_at','timestamp with time zone','NO',true),

  -- campaigns
  ('campaigns','id','uuid','NO',true),
  ('campaigns','ad_account_id','uuid','NO',false),
  ('campaigns','account_id','uuid','NO',false),
  ('campaigns','user_id','uuid','NO',false),
  ('campaigns','meta_campaign_id','text','NO',false),
  ('campaigns','name','text','YES',false),
  ('campaigns','status','text','YES',false),
  ('campaigns','effective_status','text','YES',false),
  ('campaigns','objective','text','YES',false),
  ('campaigns','daily_budget','numeric','YES',false),
  ('campaigns','lifetime_budget','numeric','YES',false),
  ('campaigns','start_time','timestamp with time zone','YES',false),
  ('campaigns','stop_time','timestamp with time zone','YES',false),
  ('campaigns','created_at','timestamp with time zone','NO',true),
  ('campaigns','updated_at','timestamp with time zone','NO',true),

  -- competitor_ads
  ('competitor_ads','id','uuid','NO',true),
  ('competitor_ads','account_id','uuid','NO',false),
  ('competitor_ads','brand_id','uuid','NO',false),
  ('competitor_ads','brand_competitor_id','uuid','YES',false),
  ('competitor_ads','user_id','uuid','NO',false),
  ('competitor_ads','foreplay_ad_id','text','YES',false),
  ('competitor_ads','foreplay_brand_id','text','YES',false),
  ('competitor_ads','meta_ad_id','text','YES',false),
  ('competitor_ads','competitor_brand_name','text','YES',false),
  ('competitor_ads','platform','text','YES',false),
  ('competitor_ads','image_url','text','YES',false),
  ('competitor_ads','video_url','text','YES',false),
  ('competitor_ads','thumbnail_url','text','YES',false),
  ('competitor_ads','copy_headline','text','YES',false),
  ('competitor_ads','copy_body','text','YES',false),
  ('competitor_ads','cta_type','text','YES',false),
  ('competitor_ads','cta_title','text','YES',false),
  ('competitor_ads','display_format','text','YES',false),
  ('competitor_ads','product_category','text','YES',false),
  ('competitor_ads','niches','text','YES',false),
  ('competitor_ads','emotional_drivers','text','YES',false),
  ('competitor_ads','full_transcription','text','YES',false),
  ('competitor_ads','is_active','boolean','YES',false),
  ('competitor_ads','days_running','numeric','YES',false),
  ('competitor_ads','est_monthly_spend','numeric','YES',false),
  ('competitor_ads','first_seen_date','date','YES',false),
  ('competitor_ads','last_seen_date','date','YES',false),
  ('competitor_ads','created_at','timestamp with time zone','NO',true),
  ('competitor_ads','updated_at','timestamp with time zone','NO',true),

  -- creative_tags
  ('creative_tags','id','uuid','NO',true),
  ('creative_tags','account_id','uuid','NO',false),
  ('creative_tags','user_id','uuid','NO',false),
  ('creative_tags','creative_id','uuid','NO',false),
  ('creative_tags','creative_source','USER-DEFINED','NO',false),
  ('creative_tags','tag_category','text','NO',false),
  ('creative_tags','tag_value','text','NO',false),
  ('creative_tags','confidence','numeric','YES',false),
  ('creative_tags','is_ai_generated','boolean','NO',true),
  ('creative_tags','is_verified','boolean','NO',true),
  ('creative_tags','created_at','timestamp with time zone','NO',true),

  -- disclaimers
  ('disclaimers','id','uuid','NO',true),
  ('disclaimers','account_id','uuid','NO',false),
  ('disclaimers','ad_account_id','uuid','NO',false),
  ('disclaimers','brand_id','uuid','YES',false),
  ('disclaimers','user_id','uuid','NO',false),
  ('disclaimers','label','text','NO',false),
  ('disclaimers','text','text','NO',false),
  ('disclaimers','created_at','timestamp with time zone','NO',true),
  ('disclaimers','updated_at','timestamp with time zone','NO',true),

  -- fatigue_diagnoses
  ('fatigue_diagnoses','id','uuid','NO',true),
  ('fatigue_diagnoses','account_id','uuid','NO',false),
  ('fatigue_diagnoses','brand_id','uuid','NO',false),
  ('fatigue_diagnoses','ad_id','uuid','NO',false),
  ('fatigue_diagnoses','adset_id','uuid','YES',false),
  ('fatigue_diagnoses','user_id','uuid','NO',false),
  ('fatigue_diagnoses','component','USER-DEFINED','NO',false),
  ('fatigue_diagnoses','severity','USER-DEFINED','NO',false),
  ('fatigue_diagnoses','status','USER-DEFINED','NO',true),
  ('fatigue_diagnoses','diagnosed_at','timestamp with time zone','NO',true),
  ('fatigue_diagnoses','dismissed_at','timestamp with time zone','YES',false),
  ('fatigue_diagnoses','dismissed_by','uuid','YES',false),
  ('fatigue_diagnoses','frequency_value','numeric','YES',false),
  ('fatigue_diagnoses','ctr_drop_pct','numeric','YES',false),
  ('fatigue_diagnoses','ctr_7d_slope','numeric','YES',false),
  ('fatigue_diagnoses','roas_drop_pct','numeric','YES',false),
  ('fatigue_diagnoses','roas_7d_slope','numeric','YES',false),
  ('fatigue_diagnoses','est_daily_waste','numeric','YES',false),
  ('fatigue_diagnoses','current_visual_tags','text','YES',false),
  ('fatigue_diagnoses','preserve_tags','text','YES',false),
  ('fatigue_diagnoses','replace_tags','text','YES',false),
  ('fatigue_diagnoses','notes','text','YES',false),
  ('fatigue_diagnoses','created_at','timestamp with time zone','NO',true),
  ('fatigue_diagnoses','updated_at','timestamp with time zone','NO',true),

  -- generated_creatives
  ('generated_creatives','id','uuid','NO',true),
  ('generated_creatives','job_id','uuid','NO',false),
  ('generated_creatives','account_id','uuid','NO',false),
  ('generated_creatives','brand_id','uuid','YES',false),
  ('generated_creatives','user_id','uuid','NO',false),
  ('generated_creatives','variant_index','integer','NO',true),
  ('generated_creatives','aspect_ratio','text','YES',false),
  ('generated_creatives','image_url','text','NO',false),
  ('generated_creatives','thumbnail_url','text','YES',false),
  ('generated_creatives','stored_image_url','text','YES',false),
  ('generated_creatives','stored_thumbnail_url','text','YES',false),
  ('generated_creatives','headline','text','YES',false),
  ('generated_creatives','primary_text','text','YES',false),
  ('generated_creatives','description','text','YES',false),
  ('generated_creatives','metadata','jsonb','NO',true),
  ('generated_creatives','status','USER-DEFINED','NO',true),
  ('generated_creatives','feedback','text','YES',false),
  ('generated_creatives','parent_ad_id','uuid','YES',false),
  ('generated_creatives','fatigue_diagnosis_id','uuid','YES',false),
  ('generated_creatives','prompt_template_id','uuid','YES',false),
  ('generated_creatives','approved_at','timestamp with time zone','YES',false),
  ('generated_creatives','approved_by','uuid','YES',false),
  ('generated_creatives','rejected_at','timestamp with time zone','YES',false),
  ('generated_creatives','rejected_by','uuid','YES',false),
  ('generated_creatives','rejection_reason','text','YES',false),
  ('generated_creatives','published_at','timestamp with time zone','YES',false),
  ('generated_creatives','published_by','uuid','YES',false),
  ('generated_creatives','published_meta_ad_id','text','YES',false),
  ('generated_creatives','storage_status','text','YES',false),
  ('generated_creatives','created_at','timestamp with time zone','NO',true),
  ('generated_creatives','updated_at','timestamp with time zone','NO',true),

  -- generation_jobs
  ('generation_jobs','id','uuid','NO',true),
  ('generation_jobs','account_id','uuid','NO',false),
  ('generation_jobs','ad_account_id','uuid','YES',false),
  ('generation_jobs','brand_id','uuid','YES',false),
  ('generation_jobs','user_id','uuid','NO',false),
  ('generation_jobs','icp_id','uuid','YES',false),
  ('generation_jobs','icp_snapshot','jsonb','YES',false),
  ('generation_jobs','goal','text','YES',false),
  ('generation_jobs','promo_scope','text','YES',false),
  ('generation_jobs','offer_type','text','YES',false),
  ('generation_jobs','product_input_method','text','YES',false),
  ('generation_jobs','product_url','text','YES',false),
  ('generation_jobs','product_image_url','text','YES',false),
  ('generation_jobs','aspect_ratios','ARRAY','NO',true),
  ('generation_jobs','promo_details','jsonb','NO',true),
  ('generation_jobs','disclaimer_ids','ARRAY','YES',true),
  ('generation_jobs','service_job_id','text','YES',false),
  ('generation_jobs','service_request_payload','jsonb','NO',true),
  ('generation_jobs','service_response_payload','jsonb','YES',false),
  ('generation_jobs','status','USER-DEFINED','NO',true),
  ('generation_jobs','trigger_type','USER-DEFINED','NO',true),
  ('generation_jobs','attempt_count','integer','YES',false),
  ('generation_jobs','credits_used','integer','YES',false),
  ('generation_jobs','error_message','text','YES',false),
  ('generation_jobs','source_ad_id','uuid','YES',false),
  ('generation_jobs','fatigue_diagnosis_id','uuid','YES',false),
  ('generation_jobs','callback_received_at','timestamp with time zone','YES',false),
  ('generation_jobs','created_at','timestamp with time zone','NO',true),
  ('generation_jobs','updated_at','timestamp with time zone','NO',true),

  -- icps
  ('icps','id','uuid','NO',true),
  ('icps','account_id','uuid','NO',false),
  ('icps','ad_account_id','uuid','NO',false),
  ('icps','brand_id','uuid','YES',false),
  ('icps','user_id','uuid','NO',false),
  ('icps','name','text','NO',false),
  ('icps','description','text','NO',false),
  ('icps','source','text','NO',true),
  ('icps','is_active','boolean','NO',true),
  ('icps','created_at','timestamp with time zone','NO',true),
  ('icps','updated_at','timestamp with time zone','NO',true),

  -- meta_connections
  ('meta_connections','id','uuid','NO',true),
  ('meta_connections','account_id','uuid','NO',false),
  ('meta_connections','user_id','uuid','NO',false),
  ('meta_connections','access_token','text','NO',false),
  ('meta_connections','token_expires_at','timestamp with time zone','YES',false),
  ('meta_connections','meta_user_id','text','YES',false),
  ('meta_connections','meta_user_name','text','YES',false),
  ('meta_connections','created_at','timestamp with time zone','NO',true),
  ('meta_connections','updated_at','timestamp with time zone','NO',true),

  -- mock_creative_library
  ('mock_creative_library','id','uuid','NO',true),
  ('mock_creative_library','image_url','text','NO',false),
  ('mock_creative_library','thumbnail_url','text','YES',false),
  ('mock_creative_library','aspect_ratio','text','YES',false),
  ('mock_creative_library','icp_keyword','text','YES',false),
  ('mock_creative_library','goal','text','YES',false),
  ('mock_creative_library','offer_name','text','YES',false),
  ('mock_creative_library','headline','text','YES',false),
  ('mock_creative_library','primary_text','text','YES',false),
  ('mock_creative_library','metadata','jsonb','NO',true),
  ('mock_creative_library','created_at','timestamp with time zone','NO',true),
  ('mock_creative_library','updated_at','timestamp with time zone','NO',true),

  -- offers
  ('offers','id','uuid','NO',true),
  ('offers','account_id','uuid','NO',false),
  ('offers','user_id','uuid','NO',false),
  ('offers','ad_account_id','uuid','NO',false),
  ('offers','brand_id','uuid','YES',false),
  ('offers','name','text','NO',false),
  ('offers','offer_type','text','NO',false),
  ('offers','discount_value','text','YES',false),
  ('offers','buy_qty','text','YES',false),
  ('offers','get_qty','text','YES',false),
  ('offers','bogo_discount','text','YES',false),
  ('offers','trial_price','text','YES',false),
  ('offers','freebie_description','text','YES',false),
  ('offers','custom_offer_headline','text','YES',false),
  ('offers','promo_code','text','YES',false),
  ('offers','start_date','timestamp with time zone','YES',false),
  ('offers','end_date','timestamp with time zone','YES',false),
  ('offers','additional_notes','text','YES',false),
  ('offers','disclaimer_ids','ARRAY','NO',true),
  ('offers','is_active','boolean','NO',true),
  ('offers','created_at','timestamp with time zone','NO',true),
  ('offers','updated_at','timestamp with time zone','NO',true),

  -- products
  ('products','id','uuid','NO',true),
  ('products','account_id','uuid','NO',false),
  ('products','brand_id','uuid','NO',false),
  ('products','user_id','uuid','NO',false),
  ('products','shopify_id','bigint','YES',false),
  ('products','title','text','YES',false),
  ('products','description','text','YES',false),
  ('products','handle','text','YES',false),
  ('products','image_urls','jsonb','YES',false),
  ('products','created_at','timestamp with time zone','NO',true),
  ('products','updated_at','timestamp with time zone','NO',true),

  -- profiles
  ('profiles','id','uuid','NO',false),
  ('profiles','email','text','YES',false),
  ('profiles','full_name','text','YES',false),
  ('profiles','meta_user_id','text','YES',false),
  ('profiles','avatar_url','text','YES',false),
  ('profiles','default_ad_account_id','uuid','YES',false),
  ('profiles','is_superadmin','boolean','NO',true),
  ('profiles','created_at','timestamp with time zone','NO',true),
  ('profiles','updated_at','timestamp with time zone','NO',true),

  -- prompt_template_performance
  ('prompt_template_performance','id','uuid','NO',true),
  ('prompt_template_performance','prompt_template_id','uuid','NO',false),
  ('prompt_template_performance','generated_creative_id','uuid','NO',false),
  ('prompt_template_performance','spend_7d','numeric','YES',false),
  ('prompt_template_performance','roas_7d','numeric','YES',false),
  ('prompt_template_performance','roas_vs_parent','numeric','YES',false),
  ('prompt_template_performance','ctr_7d','numeric','YES',false),
  ('prompt_template_performance','ctr_vs_parent','numeric','YES',false),
  ('prompt_template_performance','purchases_7d','numeric','YES',false),
  ('prompt_template_performance','is_winner','boolean','YES',false),
  ('prompt_template_performance','created_at','timestamp with time zone','NO',true),
  ('prompt_template_performance','updated_at','timestamp with time zone','NO',true),

  -- prompt_templates
  ('prompt_templates','id','uuid','NO',true),
  ('prompt_templates','account_id','uuid','YES',false),
  ('prompt_templates','user_id','uuid','NO',false),
  ('prompt_templates','name','text','NO',false),
  ('prompt_templates','use_case','text','YES',false),
  ('prompt_templates','template_text','text','NO',false),
  ('prompt_templates','model','text','YES',false),
  ('prompt_templates','parameters','jsonb','YES',false),
  ('prompt_templates','notes','text','YES',false),
  ('prompt_templates','version','integer','NO',true),
  ('prompt_templates','is_active','boolean','NO',true),
  ('prompt_templates','created_at','timestamp with time zone','NO',true),
  ('prompt_templates','updated_at','timestamp with time zone','NO',true),

  -- scene_archetypes
  ('scene_archetypes','id','uuid','NO',true),
  ('scene_archetypes','key','text','NO',false),
  ('scene_archetypes','name','text','NO',false),
  ('scene_archetypes','description','text','YES',false),
  ('scene_archetypes','is_active','boolean','NO',true),
  ('scene_archetypes','sort_order','integer','YES',false),
  ('scene_archetypes','created_at','timestamp with time zone','NO',true),
  ('scene_archetypes','updated_at','timestamp with time zone','NO',true),

  -- sync_jobs
  ('sync_jobs','id','uuid','NO',true),
  ('sync_jobs','account_id','uuid','NO',false),
  ('sync_jobs','ad_account_id','uuid','NO',false),
  ('sync_jobs','user_id','uuid','NO',false),
  ('sync_jobs','status','USER-DEFINED','NO',true),
  ('sync_jobs','phase','text','YES',false),
  ('sync_jobs','current_step','text','YES',false),
  ('sync_jobs','cursor_date','date','YES',false),
  ('sync_jobs','date_range_start','date','YES',false),
  ('sync_jobs','date_range_end','date','YES',false),
  ('sync_jobs','total_campaigns','integer','YES',false),
  ('sync_jobs','total_adsets','integer','YES',false),
  ('sync_jobs','total_ads','integer','YES',false),
  ('sync_jobs','supported_ads','integer','YES',false),
  ('sync_jobs','unsupported_ads','integer','YES',false),
  ('sync_jobs','total_creatives','integer','YES',false),
  ('sync_jobs','total_images','integer','YES',false),
  ('sync_jobs','images_downloaded','integer','YES',false),
  ('sync_jobs','error_message','text','YES',false),
  ('sync_jobs','created_at','timestamp with time zone','NO',true),
  ('sync_jobs','updated_at','timestamp with time zone','NO',true)
),
actual AS (
  SELECT
    c.table_name,
    c.column_name,
    CASE
      WHEN c.data_type = 'ARRAY' THEN 'ARRAY'
      WHEN c.udt_name LIKE 'e_%' OR c.data_type = 'USER-DEFINED' THEN 'USER-DEFINED'
      ELSE c.data_type
    END AS data_type,
    c.is_nullable,
    CASE WHEN c.column_default IS NOT NULL THEN true ELSE false END AS has_default
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
    AND c.table_name IN (SELECT DISTINCT table_name FROM expected)
),
missing_cols AS (
  SELECT e.table_name, e.column_name, 'MISSING COLUMN' AS issue,
         NULL AS expected_val, NULL AS actual_val
  FROM expected e
  LEFT JOIN actual a USING (table_name, column_name)
  WHERE a.column_name IS NULL
),
type_mismatch AS (
  SELECT
    e.table_name, e.column_name, 'TYPE MISMATCH' AS issue,
    e.data_type AS expected_val,
    a.data_type AS actual_val
  FROM expected e
  JOIN actual a USING (table_name, column_name)
  WHERE e.data_type != 'USER-DEFINED'
    AND a.data_type != 'USER-DEFINED'
    AND e.data_type != a.data_type
),
nullable_mismatch AS (
  SELECT
    e.table_name, e.column_name, 'NULLABLE MISMATCH' AS issue,
    e.is_nullable AS expected_val,
    a.is_nullable AS actual_val
  FROM expected e
  JOIN actual a USING (table_name, column_name)
  WHERE e.is_nullable != a.is_nullable
),
extra_cols AS (
  SELECT a.table_name, a.column_name, 'EXTRA COLUMN (not in Lovable)' AS issue,
         NULL AS expected_val, NULL AS actual_val
  FROM actual a
  LEFT JOIN expected e USING (table_name, column_name)
  WHERE e.column_name IS NULL
)
SELECT * FROM missing_cols
UNION ALL SELECT * FROM type_mismatch
UNION ALL SELECT * FROM nullable_mismatch
UNION ALL SELECT * FROM extra_cols
ORDER BY table_name, issue, column_name;
