import { BarChart3, Rocket, Bell, ArrowRight } from "lucide-react";
import { Section } from "./Section";
import { useInView } from "./useInView";
import benefitsCreatives from "@/assets/benefits-creatives.png";

type Benefit = {
  icon: typeof BarChart3;
  title: string;
  description: string;
};

const benefits: Benefit[] = [
  {
    icon: BarChart3,
    title: "Learn what wins",
    description: "Turn creative data into proven performance insights.",
  },
  {
    icon: Rocket,
    title: "Launch 7x faster",
    description: "Ship high-performing ads in minutes, not days.",
  },
  {
    icon: Bell,
    title: "Never miss a signal",
    description: "Auto-detect trends and act on opportunities instantly.",
  },
];

const BenefitCard = ({
  benefit,
  index,
  offsetClass,
}: {
  benefit: Benefit;
  index: number;
  offsetClass: string;
}) => {
  const { ref, visible } = useInView(0.15);
  const Icon = benefit.icon;
  return (
    <div
      ref={ref}
      style={{ transitionDelay: visible ? `${index * 100}ms` : "0ms" }}
      className={`relative bg-background rounded-2xl border border-border/60 shadow-[0_20px_50px_-20px_rgba(15,23,42,0.18)] p-6 md:p-7 w-full md:w-[300px] ${offsetClass} transition-all duration-700 ease-out ${
        visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-6"
      }`}
    >
      <div className="flex items-start justify-between">
        <div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center">
          <Icon className="w-5 h-5 text-primary" strokeWidth={2} />
        </div>
        <div className="w-9 h-9 rounded-full bg-primary flex items-center justify-center shadow-md shadow-primary/30">
          <ArrowRight className="w-4 h-4 text-primary-foreground" strokeWidth={2.25} />
        </div>
      </div>
      <h3 className="mt-6 font-display font-bold text-xl text-foreground tracking-tight">
        {benefit.title}
      </h3>
      <p className="mt-2 text-sm text-muted-foreground font-body leading-relaxed">
        {benefit.description}
      </p>
    </div>
  );
};

export const HowItWorksSection = () => {
  const { ref, visible } = useInView(0.15);
  return (
    <Section id="how-it-works" className="bg-background px-6 pt-24 md:pt-32 pb-0 overflow-hidden">
      <div className="max-w-[1200px] mx-auto">
        {/* Headline */}
        <div
          ref={ref}
          className={`text-center max-w-4xl mx-auto transition-all duration-700 ease-out ${
            visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-3"
          }`}
        >
          <h2 className="font-display font-bold text-4xl md:text-6xl lg:text-[72px] leading-[1.05] tracking-tight text-foreground">
            Unlock performance
            <br />
            at the <span className="text-primary">speed of growth.</span>
          </h2>
          <p className="mt-6 text-base md:text-lg text-muted-foreground font-body">
            Ready-to-run Meta ads built from creative learnings.
          </p>
        </div>

        {/* Cards row — staggered */}
        <div className="relative mt-16 md:mt-20">
          <div className="hidden md:flex justify-center items-start gap-6 lg:gap-10 relative z-20">
            <BenefitCard benefit={benefits[0]} index={0} offsetClass="translate-y-0" />
            <BenefitCard benefit={benefits[1]} index={1} offsetClass="translate-y-12" />
            <BenefitCard benefit={benefits[2]} index={2} offsetClass="translate-y-4" />
          </div>

          {/* Connecting dashed progress line — desktop only */}
          <ConnectingLine />

          {/* Mobile stacked */}
          <div className="md:hidden flex flex-col gap-5 relative z-20">
            {benefits.map((b, i) => (
              <BenefitCard key={b.title} benefit={b} index={i} offsetClass="" />
            ))}
          </div>

          {/* Creatives image — overlaps cards heavily */}
          <div className="relative -mt-32 md:-mt-56 lg:-mt-72 z-10">
            <img
              src={benefitsCreatives}
              alt="Examples of Meta ad creatives generated by Six Labs"
              className="w-full h-auto select-none pointer-events-none"
              draggable={false}
            />
          </div>
        </div>
      </div>
    </Section>
  );
};
